// Code generated by protoc-gen-go.
// source: uuid.proto
// DO NOT EDIT!

/*
Package uuid is a generated protocol buffer package.

It is generated from these files:
	uuid.proto

It has these top-level messages:
	UuidRequest
	UuidResponse
*/
package uuid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UuidRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *UuidRequest) Reset()                    { *m = UuidRequest{} }
func (m *UuidRequest) String() string            { return proto.CompactTextString(m) }
func (*UuidRequest) ProtoMessage()               {}
func (*UuidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UuidRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UuidResponse struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *UuidResponse) Reset()                    { *m = UuidResponse{} }
func (m *UuidResponse) String() string            { return proto.CompactTextString(m) }
func (*UuidResponse) ProtoMessage()               {}
func (*UuidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UuidResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*UuidRequest)(nil), "uuid.UuidRequest")
	proto.RegisterType((*UuidResponse)(nil), "uuid.UuidResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UuidGenerator service

type UuidGeneratorClient interface {
	Generate(ctx context.Context, in *UuidRequest, opts ...grpc.CallOption) (*UuidResponse, error)
}

type uuidGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewUuidGeneratorClient(cc *grpc.ClientConn) UuidGeneratorClient {
	return &uuidGeneratorClient{cc}
}

func (c *uuidGeneratorClient) Generate(ctx context.Context, in *UuidRequest, opts ...grpc.CallOption) (*UuidResponse, error) {
	out := new(UuidResponse)
	err := grpc.Invoke(ctx, "/uuid.UuidGenerator/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UuidGenerator service

type UuidGeneratorServer interface {
	Generate(context.Context, *UuidRequest) (*UuidResponse, error)
}

func RegisterUuidGeneratorServer(s *grpc.Server, srv UuidGeneratorServer) {
	s.RegisterService(&_UuidGenerator_serviceDesc, srv)
}

func _UuidGenerator_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UuidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UuidGeneratorServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uuid.UuidGenerator/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UuidGeneratorServer).Generate(ctx, req.(*UuidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UuidGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uuid.UuidGenerator",
	HandlerType: (*UuidGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _UuidGenerator_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uuid.proto",
}

func init() { proto.RegisterFile("uuid.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xcd, 0x4c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x64, 0xd2, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3,
	0xf3, 0x8a, 0x21, 0x6a, 0x94, 0xe4, 0xb9, 0xb8, 0x43, 0x81, 0xaa, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x40, 0x4c, 0x25, 0x25, 0x2e, 0x1e, 0x88, 0x82, 0xe2, 0x02, 0xa0, 0xae, 0x54, 0x21, 0x21, 0x2e,
	0xb0, 0xb1, 0x50, 0x25, 0x60, 0xb6, 0x51, 0x38, 0x17, 0x2f, 0x48, 0x8d, 0x7b, 0x6a, 0x5e, 0x6a,
	0x51, 0x62, 0x49, 0x7e, 0x91, 0x90, 0x1b, 0x17, 0x07, 0x94, 0x93, 0x2a, 0x24, 0xa8, 0x07, 0x76,
	0x12, 0x92, 0x2d, 0x52, 0x42, 0xc8, 0x42, 0x10, 0x73, 0x95, 0x84, 0x9b, 0x2e, 0x3f, 0x99, 0xcc,
	0xc4, 0xab, 0xc4, 0xa1, 0x5f, 0x66, 0xa8, 0x0f, 0x92, 0xb6, 0x62, 0xd4, 0x72, 0x12, 0xe0, 0xe2,
	0xcb, 0xcc, 0xd7, 0x4b, 0xc9, 0x2c, 0x4e, 0xb6, 0xb4, 0x04, 0xeb, 0x49, 0x62, 0x03, 0x3b, 0xdb,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x92, 0xa1, 0x4d, 0x85, 0xe8, 0x00, 0x00, 0x00,
}
